//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerStoneApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advocate
    {
        public string Advo_First_Name { get; set; }
        public string Advo_Last_Name { get; set; }
        public int Advo_Id { get; set; }
    }
}
