//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerStoneApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Proj_Id { get; set; }
        public int Child_Id { get; set; }
        public string Child_First_Name { get; set; }
        public string Child_Last_Name { get; set; }
        public int Guard_Id { get; set; }
        public string Guard_First_Name { get; set; }
        public string Guard_Last_Name { get; set; }
        public int Diagn_Id { get; set; }
        public string Diagn_Name { get; set; }
        public int Task_Id { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Guardian Guardian { get; set; }
        public virtual Task Task { get; set; }
    }
}
